---
blacklist:
    userid:
        - 15772169
        - 16890685
        - 8211472
        - 8717773
        - 21184161
        - 8396105
        - 19810996
        - 22244447
        - 13939351
        - 22234834
        - 20023000
        - 22343246
        - 15559691
        - 5170489
        - 13881787
        - 8937813
        - 2604591
        - 7077355
        - 10965205
        - 23221241
        - 22314338
        - 18334213
        - 917197
        - 20626177
        - 10372550
        - 17601677
        - 80007
        - 22734668
        - 4387582
        - 25477767
        - 6307867
        - 4420810
    genre:
        - comedy
        - film
        - criatividade
        - humor
        - sport
        - comedia
        - morning show
        - technology
        - interview
        - spoken
        - tech
        - mma
        - myo
        - science
        - hardtekk
        - quran
        - news
    tag:
        - empire podcast
        - comedy
        - humor
        - game
        - edgefiles
    track_type:
        - spoken
